version: "3.8"
services:
  # frontend:
  # backend:
    
  mongodb:
    image: "mongo"
    volumes: 
      - data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
      
volumes:
  data: 
    
